import { Inbox, Info, Tag, Users } from "lucide-react";
import { EmailCategoryObjectType, EmailExampleType } from "./types";

export type ChatMessageType = {
    id: string;
    sender: "Alex" | "You";
    text: string;
    time: string;
};

export const mockMessages: ChatMessageType[] = [
    {
        id: "1",
        sender: "Alex",
        text: "Hey, how's the project going?",
        time: "10:42 AM",
    },
    {
        id: "2",
        sender: "You",
        text: "Pretty well! Almost done with the last section.",
        time: "10:44 AM",
    },
    {
        id: "3",
        sender: "Alex",
        text: "Nice! Let me know if you need a review.",
        time: "10:45 AM",
    },
    {
        id: "4",
        sender: "You",
        text: "Will do, thanks!",
        time: "10:46 AM",
    },
];

export const emailCategories: EmailCategoryObjectType[] = [
    { id: null, name: "All", icon: <Inbox /> },
    { id: "promotions", name: "Promotions", icon: <Tag /> },
    { id: "social", name: "Social", icon: <Users /> },
    { id: "updates", name: "Updates", icon: <Info /> },
];

export const emailExamples: EmailExampleType[] = [
    {
        id: "1",
        from: "John Doe",
        fromEmail: "johndoe@placeholderemail.com",
        subject: "Meeting with the team",
        message: "Hi team, we have a meeting tomorrow at 10am.",
        date: "2021-01-01",
        favorite: true,
        category: "promotions",
    },
    {
        id: "2",
        from: "Jane Doe",
        fromEmail: "janedoe@placeholderemail.com",
        subject: "Reminder",
        message: "Don't forget to bring your laptop.",
        date: "2021-01-02",
        category: "promotions",
        read: true,
    },
    {
        id: "3",
        from: "John Smith",
        fromEmail: "johndoe@placeholderemail.com",
        subject: "Update on the project",
        message: "We are making great progress on the project.",
        date: "2021-01-03",
        favorite: false,
    },
    {
        id: "4",
        from: "Jane Smith",
        fromEmail: "janesmith@placeholderemail.com",
        subject: "Re: Meeting with the team",
        message: "Looking forward to it!",
        date: "2021-01-04",
        category: "social",
        read: true,
    },
    {
        id: "5",
        from: "John Doe",
        fromEmail: "johndoe@placeholderemail.com",
        subject: "Meeting",
        message: "Hi team, we have a meeting tomorrow at 10am.",
        date: "2021-01-01",
        favorite: true,
        category: "updates",
    },
    {
        id: "6",
        from: "Jane Doe",
        fromEmail: "janedoe@placeholderemail.com",
        subject: "Reminder",
        message: "Don't forget to bring your laptop.",
        date: "2021-01-02",
        category: "updates",
        read: true,
    },
    {
        id: "7",
        from: "John Smith",
        fromEmail: "johnsm@placeholderemail.com",
        subject: "Update",
        message: "We are making great progress on the project.",
        date: "2021-01-03",
        favorite: false,
        category: "social",
    },
];

export const htmlTags = [
    "a",
    "abbr",
    "address",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "bdi",
    "bdo",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "cite",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hr",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "link",
    "main",
    "map",
    "mark",
    "meta",
    "meter",
    "nav",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "picture",
    "pre",
    "progress",
    "q",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "script",
    "section",
    "select",
    "slot",
    "small",
    "source",
    "span",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
];
